export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";
export const UPDATE_INFOUSER_SUCCESS = "UPDATE_INFOUSER_SUCCESS";
export const UPDATE_INFOUSER_FAILED = "UPDATE_INFOUSER_FAILED";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const CHANGE_STATE_DESTI = "CHANGE_STATE_DESTI"
export const CHANGE_STATE_GETLOC = "CHANGE_STATE_GETLOC"
export const CHANGE_STATE_STARRATE = "CHANGE_STATE_STARRATE"
export const CHANGE_BUDGET = "CHANGE_BUDGET"

export const GET_ROOM_DETAIL_SUCCESS = "GET_ROOM_DETAIL_SUCCESS"
export const GET_ROOM_DETAIL_FAIL = "GET_ROOM_DETAIL_FAIL"

export const CHANGE_ID_HOTEL = "CHANGE_ID_HOTEL"
export const CHANGE_NUMBER_GUEST = "CHANGE_NUMBER_GUEST"
export const CHANGE_CHECKOUT_DATE = "CHANGE_CHECKOUT_DATE"
export const CHANGE_DATE_CHECKIN = "CHANGE_DATE_CHECKIN"
export const CHANGE_DATE_CHECKOUT = "CHANGE_DATE_CHECKOUT"
export const CHANGE_TOTAL_PRICE = "CHANGE_TOTAL_PRICE"
export const BOOKING_HOTEL_SUCCESS = "BOOKING_HOTEL_SUCCESS"
export const BOOKING_HOTEL_FAILED = "BOOKING_HOTEL_FAILED"
export const GET_ORDER_ID = "GET_ORDER_ID"
